/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 grapefruit.gltf --transform
Author: Meerschaum Digital (https://sketchfab.com/meerschaumdigital)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grapefruit-game-ready-2k-pbr-ae73f81896124c57a2a6b711b5011c6e
Title: Grapefruit (Game Ready / 2K PBR)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/grapefruit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Grapefruit_Grapefruit_0.geometry} material={materials.Grapefruit} position={[-7.28, 4.69, -6.79]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/grapefruit-transformed.glb')
