/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 kiwi.gltf --transform
Author: masanaga (https://sketchfab.com/tasklong)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/yellow-kiwifruit-86bf9f55ad4a419293e13284a68675bf
Title: Yellow Kiwifruit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/kiwi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.ywelow_kiwi_Model_7_u0_v0} position={[-1.01, -0.48, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/kiwi-transformed.glb')
