/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lemon.gltf --transform
Author: Zacxophone (https://sketchfab.com/Zacxophone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lemon-ab2625342f2c43fe8a383f8f9b4917ab
Title: Lemon 🍋
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lemon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Lemon_Lemon_0.geometry} material={materials.Lemon} position={[-7.01, 256.98, -107.35]} rotation={[-0.21, 0.82, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/lemon-transformed.glb')
