/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pear.gltf --transform
Author: Moshe Caine (https://sketchfab.com/mosheca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pear-photocatch-a58a3c9672fc4fe9aadf7c6f80fe52c2
Title: Pear - Photocatch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/pear-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_1} position={[-7.87, -1.12, -7.98]} rotation={[-Math.PI, 0, -1.71]} />
    </group>
  )
}

useGLTF.preload('/pear-transformed.glb')
