/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 plum.gltf --transform
Author: NAMAHAGE 120% (https://sketchfab.com/hiroyuki.ogata1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plum-normal-f43b717e9d6b4731b5c530f63a85c830
Title: Plum (Normal)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/plum-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Plum_LOD0_u0_v0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Plum_LOD0_u0_v0} />
      </group>
    </group>
  )
}

useGLTF.preload('/plum-transformed.glb')
